### ISSUE TITLE
TBM Dungeons - TODO

### ISSUE THREAD

**Issue by Skullians** [TheBonkedMinecraft/TBM_Dungeons#1]
Things to do:

- [x] Implement difficulty UI
- [x] Fix difficulty syncing issue - difficulty packet

- [ ] Implement VH-Style custom armor and weapons
- [ ] Mob / Boss Spawner (chooses from custom mobs that we define)
- [ ] Implement actual player skills
- [x] Scale mob abilities (speed, strength, etc?) depending on the player's attributes (skill), and _difficulty_
- [ ] Do Dungeons Wiki [GITBOOK]
- [ ] everything else AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
